# -*- coding: utf-8 -*-
"""Segmentasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18u9ua663YPwrQBLd0cKIJA25jCBUAZHw

# Tugas Segmentasi Kaki

Vincentius Johanes Lwie Jaya / 233408010
"""

!pip install opencv-python numpy matplotlib scikit-image

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from google.colab.patches import cv2_imshow
from sklearn.cluster import KMeans

image_url = '/content/exam.jpg'

def segment_leg_background(image_path):

    image = io.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    pixel_values = image.reshape((-1, 3))
    pixel_values = np.float32(pixel_values)

    k = 2
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)
    _, labels, centers = cv2.kmeans(pixel_values, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)

    centers = np.uint8(centers)

    segmented_image = centers[labels.flatten()]
    segmented_image = segmented_image.reshape(image.shape)

    if np.mean(centers[0]) < np.mean(centers[1]):
        mask = labels.reshape(image.shape[:2]) == 0
    else:
        mask = labels.reshape(image.shape[:2]) == 1

    result = image.copy()
    result[~mask] = [0, 0, 0]

    plt.figure(figsize=(15, 5))
    plt.subplot(131), plt.imshow(image), plt.title('Original')
    plt.subplot(132), plt.imshow(segmented_image), plt.title('Clusters')
    plt.subplot(133), plt.imshow(result), plt.title('Kaki vs Background')
    plt.show()

    return result

segment_leg_background(image_url)

def segment_leg_pants(image_path):

    image = io.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)


    lower_skin = np.array([0, 20, 70], dtype=np.uint8)
    upper_skin = np.array([20, 255, 255], dtype=np.uint8)
    skin_mask = cv2.inRange(hsv, lower_skin, upper_skin)


    lower_pants = np.array([0, 0, 0], dtype=np.uint8)
    upper_pants = np.array([180, 255, 60], dtype=np.uint8)
    pants_mask = cv2.inRange(hsv, lower_pants, upper_pants)

    combined_mask = cv2.bitwise_or(skin_mask, pants_mask)

    result = image.copy()
    result[combined_mask == 0] = [0, 0, 0]

    visualization = image.copy()
    visualization[skin_mask > 0] = [255, 0, 0]
    visualization[pants_mask > 0] = [0, 0, 255]

    plt.figure(figsize=(15, 5))
    plt.subplot(131), plt.imshow(image), plt.title('Original')
    plt.subplot(132), plt.imshow(result), plt.title('Kaki & Celana vs Background')
    plt.subplot(133), plt.imshow(visualization), plt.title('Kaki (Merah) vs Celana (Biru)')
    plt.show()

    return result, visualization


segment_leg_pants(image_url)

pip show transformers