# -*- coding: utf-8 -*-
"""NLP Word Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1Xz13JzrUPuNSCqzMeLfKgWRIv641RB

# NLP Word Cloud
Vincentius Johanes Lwie Jaya // 233408010

## FULL CODE WORD CLOUD
"""

# Install library yang diperlukan
!pip install nltk
!pip install wordcloud

# Import library yang diperlukan
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.corpus import brown
import re
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Download data yang diperlukan oleh NLTK
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('brown')

# Fungsi untuk preprocessing text
def preprocess_text(text, language='english'):
    # Tokenisasi
    tokens = word_tokenize(text)

    # Menghapus tanda baca dan angka
    tokens = [word for word in tokens if re.match(r'[a-zA-Z]', word)]

    # Menghapus stop words
    stop_words = set(stopwords.words(language))
    tokens = [word for word in tokens if word.lower() not in stop_words]

    # Stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]

    return tokens

# Ambil teks dari Brown Corpus (bahasa Inggris)
brown_text = ' '.join(brown.words()[:1000])  # Ambil 1000 kata pertama

# Contoh teks dalam bahasa Indonesia
text_id = """
Pemrosesan bahasa alami adalah cabang ilmu komputer yang fokus pada interaksi antara komputer dan manusia dalam bahasa alami.
Ini melibatkan analisis, pengertian, dan pembangkitan bahasa manusia oleh mesin.
Teknologi ini digunakan dalam berbagai aplikasi seperti asisten virtual, terjemahan mesin, dan analisis sentimen.
"""
indonesian_text = text_id

# Preprocess teks dalam bahasa Inggris
processed_text_en = preprocess_text(brown_text, language='english')

# Preprocess teks dalam bahasa Indonesia
processed_text_id = preprocess_text(indonesian_text, language='indonesian')

# Tampilkan hasil untuk bahasa Inggris
print("Teks Asli (Bahasa Inggris):")
print(brown_text[:200])  # Tampilkan 200 karakter pertama
print("\nTeks yang telah diproses (Bahasa Inggris):")
print(processed_text_en[:20])  # Tampilkan 20 kata pertama

# Tampilkan hasil untuk bahasa Indonesia
print("\nTeks Asli (Bahasa Indonesia):")
print(indonesian_text[:200])  # Tampilkan 200 karakter pertama
print("\nTeks yang telah diproses (Bahasa Indonesia):")
print(processed_text_id[:20])  # Tampilkan 20 kata pertama

# Buat Word Cloud untuk bahasa Inggris
wordcloud_en = WordCloud(width=800, height=400, background_color='white').generate(' '.join(processed_text_en))

# Tampilkan Word Cloud untuk bahasa Inggris
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_en, interpolation='bilinear')
plt.title("Word Cloud (Bahasa Inggris)")
plt.axis('off')  # Matikan sumbu
plt.show()

# Buat Word Cloud untuk bahasa Indonesia
wordcloud_id = WordCloud(width=800, height=400, background_color='white').generate(' '.join(processed_text_id))

# Tampilkan Word Cloud untuk bahasa Indonesia
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_id, interpolation='bilinear')
plt.title("Word Cloud (Bahasa Indonesia)")
plt.axis('off')  # Matikan sumbu
plt.show()